version: '3.3'
services:
  renode-build:
    build:
      context: .
      args:
       - https_proxy=http://172.17.0.1:3128
       - http_proxy=http://172.17.0.1:3128
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - "..:/workspace"
    environment:
      - https_proxy=http://172.17.0.1:3128
      - http_proxy=http://172.17.0.1:3128